name: capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip=24.3.1
  - pyyaml
  - pyarrow=21.0.0
  - hydra-core=1.3.2
  - matplotlib=3.10.6
  - pandas=2.3.3
  - numpy=2.3.4
  - jupyterlab=4.4.10
  - requests=2.32.5
  - pip:
    - mlflow==3.5.1
    - hydra-joblib-launcher==1.2.0
    - omegaconf==2.3.0
    - wandb==0.23.0