name: ml_pipeline_components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - hydra-core=1.3.2
  - pyyaml
  - pip=25.3
  - pip:
    - mlflow==3.5.1
    - hydra-joblib-launcher==1.2.0